export const PRODUCT_DATA = [
    {
      id: 1,
      name: "Wireless Earbuds",
      category: "Electronics",
      price: 59.99,
      stock: 143,
      sales: 1200,
    },
    {
      id: 2,
      name: "Leather Wallet",
      category: "Accessories",
      price: 39.99,
      stock: 89,
      sales: 800,
    },
    {
      id: 3,
      name: "Smart Watch",
      category: "Electronics",
      price: 199.99,
      stock: 56,
      sales: 650,
    },
    {
      id: 4,
      name: "Yoga Mat",
      category: "Fitness",
      price: 29.99,
      stock: 210,
      sales: 950,
    },
    {
      id: 5,
      name: "Coffee Maker",
      category: "Home",
      price: 79.99,
      stock: 78,
      sales: 720,
    },
    {
      id: 6,
      name: "Yoga Mat",
      category: "Fitness",
      price: 29.99,
      stock: 210,
      sales: 950,
    },
    {
      id: 7,
      name: "Coffee Maker",
      category: "Home",
      price: 79.99,
      stock: 78,
      sales: 720,
    },
    {
      id: 8,
      name: "Yoga Mat",
      category: "Fitness",
      price: 29.99,
      stock: 210,
      sales: 950,
    },
    {
      id: 9,
      name: "Coffee Maker",
      category: "Home",
      price: 79.99,
      stock: 78,
      sales: 720,
    },
  ];

